### ISSUE TITLE
Add this as a dired action

### ISSUE THREAD

**Issue by tecosaur** [jacksonbenete/emacs-checksum#1]
Would be nice if you could:

- Mark `abc.zyz` in dired and `abc.xyz.md5`
- Call emacs-checksum
- _It does the thing_

:slightly_smiling_face:

**Comment by jacksonbenete** [comment]
This is a very good idea!

I will take some time to study dired next week.

But I'm accepting Pull Requests if someone will make it happens faster. :P

**Comment by tecosaur** [comment]
I can't say I'm actually using this / likely to PR, just thought I'd share the thought :slightly_smiling_face:

**Comment by tecosaur** [comment]
Nice!
