### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by phoe** [jacksonbenete/emacs-checksum#2]
> There is a name-conflict between `COMMON-LISP:DESCRIBE` and `UNIX-OPTS:DESCRIBE`.

You can fix this by making a shadowing import in your `defpackage` form instead of just using. See http://www.flownet.com/gat/packages.pdf for more details on the package system.

**Comment by jacksonbenete** [comment]
Thank you!
This will certainly help in my general understanding about packages as well.
